Run all js tests:
  $ ecma-sl test --harness harness.js **/*.js | sort -h
                ECMA-SL Test
  ----------------------------------------
  ----------------------------------------
  Test Failure: regex/regex_utf16.js
  Test Successful: array/array.js
  Test Successful: array/array_cons_length.js
  Test Successful: array/array_sort.js
  Test Successful: regex/regex_1.js
  Test Successful: regex/regex_10.js
  Test Successful: regex/regex_11.js
  Test Successful: regex/regex_12.js
  Test Successful: regex/regex_13.js
  Test Successful: regex/regex_14.js
  Test Successful: regex/regex_15.js
  Test Successful: regex/regex_16.js
  Test Successful: regex/regex_17.js
  Test Successful: regex/regex_18.js
  Test Successful: regex/regex_19.js
  Test Successful: regex/regex_2.js
  Test Successful: regex/regex_20.js
  Test Successful: regex/regex_21.js
  Test Successful: regex/regex_22.js
  Test Successful: regex/regex_23.js
  Test Successful: regex/regex_24.js
  Test Successful: regex/regex_25.js
  Test Successful: regex/regex_26.js
  Test Successful: regex/regex_27.js
  Test Successful: regex/regex_28.js
  Test Successful: regex/regex_29.js
  Test Successful: regex/regex_3.js
  Test Successful: regex/regex_30.js
  Test Successful: regex/regex_31.js
  Test Successful: regex/regex_32.js
  Test Successful: regex/regex_33.js
  Test Successful: regex/regex_34.js
  Test Successful: regex/regex_35.js
  Test Successful: regex/regex_36.js
  Test Successful: regex/regex_37.js
  Test Successful: regex/regex_38.js
  Test Successful: regex/regex_39.js
  Test Successful: regex/regex_4.js
  Test Successful: regex/regex_40.js
  Test Successful: regex/regex_41.js
  Test Successful: regex/regex_42.js
  Test Successful: regex/regex_43.js
  Test Successful: regex/regex_44.js
  Test Successful: regex/regex_45.js
  Test Successful: regex/regex_46.js
  Test Successful: regex/regex_47.js
  Test Successful: regex/regex_48.js
  Test Successful: regex/regex_49.js
  Test Successful: regex/regex_5.js
  Test Successful: regex/regex_50.js
  Test Successful: regex/regex_51.js
  Test Successful: regex/regex_52.js
  Test Successful: regex/regex_53.js
  Test Successful: regex/regex_54.js
  Test Successful: regex/regex_55.js
  Test Successful: regex/regex_56.js
  Test Successful: regex/regex_57.js
  Test Successful: regex/regex_58.js
  Test Successful: regex/regex_59.js
  Test Successful: regex/regex_6.js
  Test Successful: regex/regex_60.js
  Test Successful: regex/regex_61.js
  Test Successful: regex/regex_62.js
  Test Successful: regex/regex_63.js
  Test Successful: regex/regex_64.js
  Test Successful: regex/regex_65.js
  Test Successful: regex/regex_66.js
  Test Successful: regex/regex_67.js
  Test Successful: regex/regex_68.js
  Test Successful: regex/regex_69.js
  Test Successful: regex/regex_7.js
  Test Successful: regex/regex_70.js
  Test Successful: regex/regex_71.js
  Test Successful: regex/regex_72.js
  Test Successful: regex/regex_73.js
  Test Successful: regex/regex_74.js
  Test Successful: regex/regex_75.js
  Test Successful: regex/regex_8.js
  Test Successful: regex/regex_9.js
  Test Successful: simple/catch.js
  Test Successful: simple/events.js
  Test Successful: simple/flow.js
  Test Successful: simple/forin.js
  Test Successful: simple/function.js
  Test Successful: simple/json.js
  Test Successful: simple/log.js
  Test Successful: simple/map.js
  Test Successful: simple/object.js
  Test Successful: simple/primes.js
  Test Successful: simple/queue.js
  Test Successful: simple/string.js
  Test Successful: simple/variable.js
