Run regex js tests:
  $ cd regex && ecma-sl test --harness ../harness.js . | sort -h
                ECMA-SL Test
  ----------------------------------------
  ----------------------------------------
  Test Failure: ./regex_utf16.js
  Test Successful: ./regex_1.js
  Test Successful: ./regex_10.js
  Test Successful: ./regex_11.js
  Test Successful: ./regex_12.js
  Test Successful: ./regex_13.js
  Test Successful: ./regex_14.js
  Test Successful: ./regex_15.js
  Test Successful: ./regex_16.js
  Test Successful: ./regex_17.js
  Test Successful: ./regex_18.js
  Test Successful: ./regex_19.js
  Test Successful: ./regex_2.js
  Test Successful: ./regex_20.js
  Test Successful: ./regex_21.js
  Test Successful: ./regex_22.js
  Test Successful: ./regex_23.js
  Test Successful: ./regex_24.js
  Test Successful: ./regex_25.js
  Test Successful: ./regex_26.js
  Test Successful: ./regex_27.js
  Test Successful: ./regex_28.js
  Test Successful: ./regex_29.js
  Test Successful: ./regex_3.js
  Test Successful: ./regex_30.js
  Test Successful: ./regex_31.js
  Test Successful: ./regex_32.js
  Test Successful: ./regex_33.js
  Test Successful: ./regex_34.js
  Test Successful: ./regex_35.js
  Test Successful: ./regex_36.js
  Test Successful: ./regex_37.js
  Test Successful: ./regex_38.js
  Test Successful: ./regex_39.js
  Test Successful: ./regex_4.js
  Test Successful: ./regex_40.js
  Test Successful: ./regex_41.js
  Test Successful: ./regex_42.js
  Test Successful: ./regex_43.js
  Test Successful: ./regex_44.js
  Test Successful: ./regex_45.js
  Test Successful: ./regex_46.js
  Test Successful: ./regex_47.js
  Test Successful: ./regex_48.js
  Test Successful: ./regex_49.js
  Test Successful: ./regex_5.js
  Test Successful: ./regex_50.js
  Test Successful: ./regex_51.js
  Test Successful: ./regex_52.js
  Test Successful: ./regex_53.js
  Test Successful: ./regex_54.js
  Test Successful: ./regex_55.js
  Test Successful: ./regex_56.js
  Test Successful: ./regex_57.js
  Test Successful: ./regex_58.js
  Test Successful: ./regex_59.js
  Test Successful: ./regex_6.js
  Test Successful: ./regex_60.js
  Test Successful: ./regex_61.js
  Test Successful: ./regex_62.js
  Test Successful: ./regex_63.js
  Test Successful: ./regex_64.js
  Test Successful: ./regex_65.js
  Test Successful: ./regex_66.js
  Test Successful: ./regex_67.js
  Test Successful: ./regex_68.js
  Test Successful: ./regex_69.js
  Test Successful: ./regex_7.js
  Test Successful: ./regex_70.js
  Test Successful: ./regex_71.js
  Test Successful: ./regex_72.js
  Test Successful: ./regex_73.js
  Test Successful: ./regex_74.js
  Test Successful: ./regex_75.js
  Test Successful: ./regex_8.js
  Test Successful: ./regex_9.js
