let%test_unit _ = Test.syntax_test "example/basic/ok_typing.esl"
let%test_unit _ = Test.syntax_test "example/basic/ok_primitive.esl"
let%test_unit _ = Test.syntax_test "example/basic/ok_extra_types.esl"
let%test_unit _ = Test.syntax_test "example/function/ok_function.esl"
let%test_unit _ = Test.syntax_test "example/nary/ok_union.esl"
let%test_unit _ = Test.syntax_test "example/object/ok_object.esl"
let%test_unit _ = Test.syntax_test "example/object/ok_opt_prop.esl"