name: Run Test262 Benchmarks

on:
  workflow_dispatch

jobs:
  test:
    env:
      TERM: screen-256color
      OCAML_COMPILER: 4.14

    strategy:
      fail-fast: false

    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup OCaml ${{ env.OCAML_COMPILER }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ env.OCAML_COMPILER }}

      - name: Install dependencies
        run: opam install -y . --deps-only --with-test

      - name: Build
        run: opam exec -- dune build @install

      - name: Run Test262
        # The workflow should succeed even if `test` has nonzero return code
        continue-on-error: true
        run: |
          opam exec -- dune exec -- ecma-sl test --type test262 test/test262/tests/ --webhook-url "$SLACK_WEBHOOK_URL" > results-test262_${{ github.sha }}.txt

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: test262-results
          path: test262-results.txt
